# Generated by Django 5.2.14 on 2026-05-23 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('postal_code', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('subtotal', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('total', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('credit_wallet', 'افزایش اعتبار و پرداخت از کیف پول'), ('online', 'پرداخت اینترنتی هوشمند'), ('cod', 'پرداخت هنگام دریافت')], max_length=20)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
