# Generated by Django 5.2.14 on 2026-06-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='national_code',
        ),
    ]
