# Generated by Django 6.0 on 2026-05-02 12:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_brand_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from=models.CharField(max_length=100), unique=True),
            preserve_default=False,
        ),
    ]
