# Generated by Django 5.2.14 on 2026-05-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_productnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productnotification',
            name='is_sent',
        ),
        migrations.AlterField(
            model_name='productnotification',
            name='method',
            field=models.CharField(max_length=10),
        ),
    ]
