# Generated by Django 5.2.14 on 2026-05-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='variants', to='catalog.productimage'),
        ),
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='variants/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
