# Generated by Django 5.2.14 on 2026-06-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0041_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=1, upload_to='category_icons/'),
            preserve_default=False,
        ),
    ]
