# Generated by Django 5.2.14 on 2026-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان تخفیف'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_amazing',
            field=models.BooleanField(default=False, verbose_name='نمایش در بخش شگفت\u200cانگیز'),
        ),
    ]
