# Generated by Django 5.2.14 on 2026-06-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_product_discount_end_date_product_is_amazing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='پایان پیشنهاد'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False, verbose_name='پیشنهاد لحظه\u200cای'),
        ),
    ]
