# Generated by Django 5.2.14 on 2026-06-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_product_flash_sale_end_product_is_flash_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flash_sale_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_flash_sale',
        ),
        migrations.AddField(
            model_name='product',
            name='is_moment',
            field=models.BooleanField(default=False, verbose_name='نمایش در پیشنهاد لحظه\u200cای'),
        ),
        migrations.AddField(
            model_name='product',
            name='moment_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای پیشنهاد'),
        ),
    ]
