# Generated by Django 5.2.14 on 2026-06-14 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0045_remove_product_flash_sale_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(verbose_name='درصد تخفیف')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='catalog.product')),
            ],
            options={
                'verbose_name': 'تخفیف محصول',
                'verbose_name_plural': 'تخفیف\u200cهای محصولات',
            },
        ),
    ]
