# Generated by Django 5.2.14 on 2026-06-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0046_productdiscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_end_date',
        ),
    ]
