# Generated by Django 5.2.14 on 2026-06-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_alter_productdiscount_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع'),
        ),
    ]
