# Generated by Django 5.2.14 on 2026-06-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0051_delete_newsletter_alter_productvariant_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
